# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SmartGreen.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(751, 539)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(241, 255, 225);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabClient = QtGui.QWidget()
        self.tabClient.setObjectName(_fromUtf8("tabClient"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabClient)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelGreenTechCl = QtGui.QLabel(self.tabClient)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelGreenTechCl.setFont(font)
        self.labelGreenTechCl.setStyleSheet(_fromUtf8("color: rgb(0, 255, 0);"))
        self.labelGreenTechCl.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGreenTechCl.setObjectName(_fromUtf8("labelGreenTechCl"))
        self.verticalLayout_3.addWidget(self.labelGreenTechCl)
        self.labelGreenGroceryCl = QtGui.QLabel(self.tabClient)
        self.labelGreenGroceryCl.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.labelGreenGroceryCl.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGreenGroceryCl.setObjectName(_fromUtf8("labelGreenGroceryCl"))
        self.verticalLayout_3.addWidget(self.labelGreenGroceryCl)
        self.lineOnTop_2 = QtGui.QFrame(self.tabClient)
        self.lineOnTop_2.setFrameShape(QtGui.QFrame.HLine)
        self.lineOnTop_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineOnTop_2.setObjectName(_fromUtf8("lineOnTop_2"))
        self.verticalLayout_3.addWidget(self.lineOnTop_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelCashier = QtGui.QLabel(self.tabClient)
        self.labelCashier.setObjectName(_fromUtf8("labelCashier"))
        self.horizontalLayout.addWidget(self.labelCashier)
        self.comboBoxCashier = QtGui.QComboBox(self.tabClient)
        self.comboBoxCashier.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBoxCashier.setObjectName(_fromUtf8("comboBoxCashier"))
        self.comboBoxCashier.addItem(_fromUtf8(""))
        self.comboBoxCashier.addItem(_fromUtf8(""))
        self.comboBoxCashier.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxCashier)
        self.line_23 = QtGui.QFrame(self.tabClient)
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.horizontalLayout.addWidget(self.line_23)
        self.labelAcct = QtGui.QLabel(self.tabClient)
        self.labelAcct.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAcct.setObjectName(_fromUtf8("labelAcct"))
        self.horizontalLayout.addWidget(self.labelAcct)
        self.comboBoxAcct = QtGui.QComboBox(self.tabClient)
        self.comboBoxAcct.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBoxAcct.setObjectName(_fromUtf8("comboBoxAcct"))
        self.comboBoxAcct.addItem(_fromUtf8(""))
        self.comboBoxAcct.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxAcct)
        self.line_10 = QtGui.QFrame(self.tabClient)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout.addWidget(self.line_10)
        self.labelDateCl = QtGui.QLabel(self.tabClient)
        self.labelDateCl.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDateCl.setObjectName(_fromUtf8("labelDateCl"))
        self.horizontalLayout.addWidget(self.labelDateCl)
        self.dateEditCl = QtGui.QDateEdit(self.tabClient)
        self.dateEditCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dateEditCl.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 2, 26), QtCore.QTime(0, 0, 0)))
        self.dateEditCl.setObjectName(_fromUtf8("dateEditCl"))
        self.horizontalLayout.addWidget(self.dateEditCl)
        self.line_9 = QtGui.QFrame(self.tabClient)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout.addWidget(self.line_9)
        self.labelTimeCl = QtGui.QLabel(self.tabClient)
        self.labelTimeCl.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTimeCl.setObjectName(_fromUtf8("labelTimeCl"))
        self.horizontalLayout.addWidget(self.labelTimeCl)
        self.timeEditCl = QtGui.QTimeEdit(self.tabClient)
        self.timeEditCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.timeEditCl.setTime(QtCore.QTime(14, 24, 44))
        self.timeEditCl.setObjectName(_fromUtf8("timeEditCl"))
        self.horizontalLayout.addWidget(self.timeEditCl)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.lineOnTop = QtGui.QFrame(self.tabClient)
        self.lineOnTop.setFrameShape(QtGui.QFrame.HLine)
        self.lineOnTop.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineOnTop.setObjectName(_fromUtf8("lineOnTop"))
        self.verticalLayout_4.addWidget(self.lineOnTop)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tableViewClient = QtGui.QTableView(self.tabClient)
        self.tableViewClient.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewClient.sizePolicy().hasHeightForWidth())
        self.tableViewClient.setSizePolicy(sizePolicy)
        self.tableViewClient.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableViewClient.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tableViewClient.setObjectName(_fromUtf8("tableViewClient"))
        self.horizontalLayout_4.addWidget(self.tableViewClient)
        self.line_7 = QtGui.QFrame(self.tabClient)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_4.addWidget(self.line_7)
        self.formLayoutClient = QtGui.QFormLayout()
        self.formLayoutClient.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutClient.setContentsMargins(10, -1, 10, -1)
        self.formLayoutClient.setObjectName(_fromUtf8("formLayoutClient"))
        self.labelSubTotalCl = QtGui.QLabel(self.tabClient)
        self.labelSubTotalCl.setObjectName(_fromUtf8("labelSubTotalCl"))
        self.formLayoutClient.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelSubTotalCl)
        self.lineEditSubTotalCl = QtGui.QLineEdit(self.tabClient)
        self.lineEditSubTotalCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditSubTotalCl.setObjectName(_fromUtf8("lineEditSubTotalCl"))
        self.formLayoutClient.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditSubTotalCl)
        self.labelTaxCl = QtGui.QLabel(self.tabClient)
        self.labelTaxCl.setObjectName(_fromUtf8("labelTaxCl"))
        self.formLayoutClient.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTaxCl)
        self.lineEditTaxCl = QtGui.QLineEdit(self.tabClient)
        self.lineEditTaxCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditTaxCl.setObjectName(_fromUtf8("lineEditTaxCl"))
        self.formLayoutClient.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditTaxCl)
        self.labelDiscountCl = QtGui.QLabel(self.tabClient)
        self.labelDiscountCl.setObjectName(_fromUtf8("labelDiscountCl"))
        self.formLayoutClient.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelDiscountCl)
        self.lineEditDiscountCl = QtGui.QLineEdit(self.tabClient)
        self.lineEditDiscountCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditDiscountCl.setObjectName(_fromUtf8("lineEditDiscountCl"))
        self.formLayoutClient.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditDiscountCl)
        self.labelTotalCl = QtGui.QLabel(self.tabClient)
        self.labelTotalCl.setObjectName(_fromUtf8("labelTotalCl"))
        self.formLayoutClient.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelTotalCl)
        self.lineEditTotalCl = QtGui.QLineEdit(self.tabClient)
        self.lineEditTotalCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditTotalCl.setObjectName(_fromUtf8("lineEditTotalCl"))
        self.formLayoutClient.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditTotalCl)
        self.labelReceivedCl = QtGui.QLabel(self.tabClient)
        self.labelReceivedCl.setObjectName(_fromUtf8("labelReceivedCl"))
        self.formLayoutClient.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelReceivedCl)
        self.lineEditReceivedCl = QtGui.QLineEdit(self.tabClient)
        self.lineEditReceivedCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditReceivedCl.setObjectName(_fromUtf8("lineEditReceivedCl"))
        self.formLayoutClient.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditReceivedCl)
        self.labelBalanceCl = QtGui.QLabel(self.tabClient)
        self.labelBalanceCl.setObjectName(_fromUtf8("labelBalanceCl"))
        self.formLayoutClient.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelBalanceCl)
        self.lineEditBalanceCl = QtGui.QLineEdit(self.tabClient)
        self.lineEditBalanceCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditBalanceCl.setObjectName(_fromUtf8("lineEditBalanceCl"))
        self.formLayoutClient.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditBalanceCl)
        self.bnNextCustomerCl = QtGui.QPushButton(self.tabClient)
        self.bnNextCustomerCl.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bnNextCustomerCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                      "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                                      "background-color: rgb(155, 162, 255);\n"
                                                      "background-color: rgb(85, 170, 255);"))
        self.bnNextCustomerCl.setObjectName(_fromUtf8("bnNextCustomerCl"))
        self.formLayoutClient.setWidget(6, QtGui.QFormLayout.LabelRole, self.bnNextCustomerCl)
        self.bnCalculateCl = QtGui.QPushButton(self.tabClient)
        self.bnCalculateCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                   "background-color: rgb(155, 162, 255);\n"
                                                   "background-color: rgb(85, 170, 255);"))
        self.bnCalculateCl.setObjectName(_fromUtf8("bnCalculateCl"))
        self.formLayoutClient.setWidget(6, QtGui.QFormLayout.FieldRole, self.bnCalculateCl)
        self.horizontalLayout_4.addLayout(self.formLayoutClient)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.line_27 = QtGui.QFrame(self.tabClient)
        self.line_27.setFrameShape(QtGui.QFrame.HLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.verticalLayout_4.addWidget(self.line_27)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelSearchCl = QtGui.QLabel(self.tabClient)
        self.labelSearchCl.setStyleSheet(_fromUtf8("font: 75 9pt \"MS Shell Dlg 2\";"))
        self.labelSearchCl.setObjectName(_fromUtf8("labelSearchCl"))
        self.horizontalLayout_2.addWidget(self.labelSearchCl)
        self.lineEditSearchCl = QtGui.QLineEdit(self.tabClient)
        self.lineEditSearchCl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditSearchCl.setText(_fromUtf8(""))
        self.lineEditSearchCl.setPlaceholderText(_fromUtf8(""))
        self.lineEditSearchCl.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditSearchCl.setObjectName(_fromUtf8("lineEditSearchCl"))
        self.horizontalLayout_2.addWidget(self.lineEditSearchCl)
        self.bnSearchCl = QtGui.QPushButton(self.tabClient)
        self.bnSearchCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                "background-color: rgb(155, 162, 255);\n"
                                                "background-color: rgb(85, 170, 255);"))
        self.bnSearchCl.setObjectName(_fromUtf8("bnSearchCl"))
        self.horizontalLayout_2.addWidget(self.bnSearchCl)
        self.line_8 = QtGui.QFrame(self.tabClient)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_2.addWidget(self.line_8)
        self.bnAddCl = QtGui.QPushButton(self.tabClient)
        self.bnAddCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                             "background-color: rgb(155, 162, 255);\n"
                                             "background-color: rgb(85, 170, 255);"))
        self.bnAddCl.setObjectName(_fromUtf8("bnAddCl"))
        self.horizontalLayout_2.addWidget(self.bnAddCl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.lineOnTop2 = QtGui.QFrame(self.tabClient)
        self.lineOnTop2.setFrameShape(QtGui.QFrame.HLine)
        self.lineOnTop2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineOnTop2.setObjectName(_fromUtf8("lineOnTop2"))
        self.verticalLayout_4.addWidget(self.lineOnTop2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bnPrintCl = QtGui.QPushButton(self.tabClient)
        self.bnPrintCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                               "background-color: rgb(155, 162, 255);\n"
                                               "background-color: rgb(85, 170, 255);"))
        self.bnPrintCl.setObjectName(_fromUtf8("bnPrintCl"))
        self.horizontalLayout_3.addWidget(self.bnPrintCl)
        self.line = QtGui.QFrame(self.tabClient)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.bnSaveCl = QtGui.QPushButton(self.tabClient)
        self.bnSaveCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                              "background-color: rgb(155, 162, 255);\n"
                                              "background-color: rgb(85, 170, 255);"))
        self.bnSaveCl.setObjectName(_fromUtf8("bnSaveCl"))
        self.horizontalLayout_3.addWidget(self.bnSaveCl)
        self.line_3 = QtGui.QFrame(self.tabClient)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_3.addWidget(self.line_3)
        self.bnCancelCl = QtGui.QPushButton(self.tabClient)
        self.bnCancelCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                "background-color: rgb(155, 162, 255);\n"
                                                "background-color: rgb(85, 170, 255);"))
        self.bnCancelCl.setObjectName(_fromUtf8("bnCancelCl"))
        self.horizontalLayout_3.addWidget(self.bnCancelCl)
        self.line_4 = QtGui.QFrame(self.tabClient)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_3.addWidget(self.line_4)
        self.bnRefreshCl = QtGui.QPushButton(self.tabClient)
        self.bnRefreshCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                 "background-color: rgb(155, 162, 255);\n"
                                                 "background-color: rgb(85, 170, 255);"))
        self.bnRefreshCl.setObjectName(_fromUtf8("bnRefreshCl"))
        self.horizontalLayout_3.addWidget(self.bnRefreshCl)
        self.line_6 = QtGui.QFrame(self.tabClient)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_3.addWidget(self.line_6)
        self.bnDeleteCl = QtGui.QPushButton(self.tabClient)
        self.bnDeleteCl.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                "background-color: rgb(155, 162, 255);\n"
                                                "background-color: rgb(85, 170, 255);"))
        self.bnDeleteCl.setObjectName(_fromUtf8("bnDeleteCl"))
        self.horizontalLayout_3.addWidget(self.bnDeleteCl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lineOnBottom_2 = QtGui.QFrame(self.tabClient)
        self.lineOnBottom_2.setFrameShape(QtGui.QFrame.HLine)
        self.lineOnBottom_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineOnBottom_2.setObjectName(_fromUtf8("lineOnBottom_2"))
        self.verticalLayout_4.addWidget(self.lineOnBottom_2)
        self.labelDesignedCl = QtGui.QLabel(self.tabClient)
        self.labelDesignedCl.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 127);\n"
                                                     "color: rgb(255, 0, 0);\n"
                                                     "font: 8pt \"Lucida Handwriting\";"))
        self.labelDesignedCl.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDesignedCl.setObjectName(_fromUtf8("labelDesignedCl"))
        self.verticalLayout_4.addWidget(self.labelDesignedCl)
        self.tabWidget.addTab(self.tabClient, _fromUtf8(""))
        self.tabAdmin = QtGui.QWidget()
        self.tabAdmin.setObjectName(_fromUtf8("tabAdmin"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabAdmin)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelGreenTechAd = QtGui.QLabel(self.tabAdmin)
        self.labelGreenTechAd.setStyleSheet(_fromUtf8("color: rgb(0, 255, 0);"))
        self.labelGreenTechAd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGreenTechAd.setObjectName(_fromUtf8("labelGreenTechAd"))
        self.verticalLayout_5.addWidget(self.labelGreenTechAd)
        self.labelGreenGroceryAd = QtGui.QLabel(self.tabAdmin)
        self.labelGreenGroceryAd.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.labelGreenGroceryAd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGreenGroceryAd.setObjectName(_fromUtf8("labelGreenGroceryAd"))
        self.verticalLayout_5.addWidget(self.labelGreenGroceryAd)
        self.line_12 = QtGui.QFrame(self.tabAdmin)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout_5.addWidget(self.line_12)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.labelAdmin = QtGui.QLabel(self.tabAdmin)
        self.labelAdmin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAdmin.setObjectName(_fromUtf8("labelAdmin"))
        self.horizontalLayout_12.addWidget(self.labelAdmin)
        self.comboBoxAdmin = QtGui.QComboBox(self.tabAdmin)
        self.comboBoxAdmin.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBoxAdmin.setObjectName(_fromUtf8("comboBoxAdmin"))
        self.comboBoxAdmin.addItem(_fromUtf8(""))
        self.comboBoxAdmin.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBoxAdmin)
        self.line_24 = QtGui.QFrame(self.tabAdmin)
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.horizontalLayout_12.addWidget(self.line_24)
        self.labelDateAd = QtGui.QLabel(self.tabAdmin)
        self.labelDateAd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDateAd.setObjectName(_fromUtf8("labelDateAd"))
        self.horizontalLayout_12.addWidget(self.labelDateAd)
        self.dateEditAd = QtGui.QDateEdit(self.tabAdmin)
        self.dateEditAd.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dateEditAd.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 2, 26), QtCore.QTime(0, 0, 0)))
        self.dateEditAd.setObjectName(_fromUtf8("dateEditAd"))
        self.horizontalLayout_12.addWidget(self.dateEditAd)
        self.line_25 = QtGui.QFrame(self.tabAdmin)
        self.line_25.setFrameShape(QtGui.QFrame.VLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.horizontalLayout_12.addWidget(self.line_25)
        self.labelTimeAd = QtGui.QLabel(self.tabAdmin)
        self.labelTimeAd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTimeAd.setObjectName(_fromUtf8("labelTimeAd"))
        self.horizontalLayout_12.addWidget(self.labelTimeAd)
        self.timeEditAd = QtGui.QTimeEdit(self.tabAdmin)
        self.timeEditAd.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.timeEditAd.setTime(QtCore.QTime(14, 24, 44))
        self.timeEditAd.setObjectName(_fromUtf8("timeEditAd"))
        self.horizontalLayout_12.addWidget(self.timeEditAd)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.line_11 = QtGui.QFrame(self.tabAdmin)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_5.addWidget(self.line_11)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.tableViewAdmin = QtGui.QTableView(self.tabAdmin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewAdmin.sizePolicy().hasHeightForWidth())
        self.tableViewAdmin.setSizePolicy(sizePolicy)
        self.tableViewAdmin.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tableViewAdmin.setObjectName(_fromUtf8("tableViewAdmin"))
        self.horizontalLayout_16.addWidget(self.tableViewAdmin)
        self.line_19 = QtGui.QFrame(self.tabAdmin)
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.horizontalLayout_16.addWidget(self.line_19)
        self.formLayoutAdmin = QtGui.QFormLayout()
        self.formLayoutAdmin.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutAdmin.setContentsMargins(10, 10, 10, -1)
        self.formLayoutAdmin.setHorizontalSpacing(28)
        self.formLayoutAdmin.setVerticalSpacing(11)
        self.formLayoutAdmin.setObjectName(_fromUtf8("formLayoutAdmin"))
        self.labelTotalUnitsAd = QtGui.QLabel(self.tabAdmin)
        self.labelTotalUnitsAd.setObjectName(_fromUtf8("labelTotalUnitsAd"))
        self.formLayoutAdmin.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelTotalUnitsAd)
        self.lineEditTotalUnitsAd = QtGui.QLineEdit(self.tabAdmin)
        self.lineEditTotalUnitsAd.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditTotalUnitsAd.setObjectName(_fromUtf8("lineEditTotalUnitsAd"))
        self.formLayoutAdmin.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditTotalUnitsAd)
        self.labelTotalAmount = QtGui.QLabel(self.tabAdmin)
        self.labelTotalAmount.setObjectName(_fromUtf8("labelTotalAmount"))
        self.formLayoutAdmin.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTotalAmount)
        self.lineEditTotalAmountAd = QtGui.QLineEdit(self.tabAdmin)
        self.lineEditTotalAmountAd.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditTotalAmountAd.setObjectName(_fromUtf8("lineEditTotalAmountAd"))
        self.formLayoutAdmin.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditTotalAmountAd)
        self.bnNewEntryAd = QtGui.QPushButton(self.tabAdmin)
        self.bnNewEntryAd.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                  "background-color: rgb(155, 162, 255);\n"
                                                  "background-color: rgb(85, 170, 255);"))
        self.bnNewEntryAd.setObjectName(_fromUtf8("bnNewEntryAd"))
        self.formLayoutAdmin.setWidget(2, QtGui.QFormLayout.LabelRole, self.bnNewEntryAd)
        self.bnCalculateAd = QtGui.QPushButton(self.tabAdmin)
        self.bnCalculateAd.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                   "background-color: rgb(155, 162, 255);\n"
                                                   "background-color: rgb(85, 170, 255);"))
        self.bnCalculateAd.setObjectName(_fromUtf8("bnCalculateAd"))
        self.formLayoutAdmin.setWidget(2, QtGui.QFormLayout.FieldRole, self.bnCalculateAd)
        self.bnRefreshAd = QtGui.QPushButton(self.tabAdmin)
        self.bnRefreshAd.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                 "background-color: rgb(155, 162, 255);\n"
                                                 "background-color: rgb(85, 170, 255);"))
        self.bnRefreshAd.setObjectName(_fromUtf8("bnRefreshAd"))
        self.formLayoutAdmin.setWidget(3, QtGui.QFormLayout.FieldRole, self.bnRefreshAd)
        self.horizontalLayout_16.addLayout(self.formLayoutAdmin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.line_26 = QtGui.QFrame(self.tabAdmin)
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.verticalLayout_6.addWidget(self.line_26)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.labelSearchAd = QtGui.QLabel(self.tabAdmin)
        self.labelSearchAd.setStyleSheet(_fromUtf8("font: 75 9pt \"MS Shell Dlg 2\";"))
        self.labelSearchAd.setObjectName(_fromUtf8("labelSearchAd"))
        self.horizontalLayout_18.addWidget(self.labelSearchAd)
        self.lineEditSearchAd = QtGui.QLineEdit(self.tabAdmin)
        self.lineEditSearchAd.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditSearchAd.setObjectName(_fromUtf8("lineEditSearchAd"))
        self.horizontalLayout_18.addWidget(self.lineEditSearchAd)
        self.bnSearchAd = QtGui.QPushButton(self.tabAdmin)
        self.bnSearchAd.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                "background-color: rgb(155, 162, 255);\n"
                                                "background-color: rgb(85, 170, 255);"))
        self.bnSearchAd.setObjectName(_fromUtf8("bnSearchAd"))
        self.horizontalLayout_18.addWidget(self.bnSearchAd)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.line_14 = QtGui.QFrame(self.tabAdmin)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.verticalLayout_6.addWidget(self.line_14)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.bnPrintAd = QtGui.QPushButton(self.tabAdmin)
        self.bnPrintAd.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                               "background-color: rgb(155, 162, 255);\n"
                                               "background-color: rgb(85, 170, 255);"))
        self.bnPrintAd.setObjectName(_fromUtf8("bnPrintAd"))
        self.horizontalLayout_19.addWidget(self.bnPrintAd)
        self.line_17 = QtGui.QFrame(self.tabAdmin)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.horizontalLayout_19.addWidget(self.line_17)
        self.bnDeleteAd = QtGui.QPushButton(self.tabAdmin)
        self.bnDeleteAd.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                "background-color: rgb(155, 162, 255);\n"
                                                "background-color: rgb(85, 170, 255);"))
        self.bnDeleteAd.setObjectName(_fromUtf8("bnDeleteAd"))
        self.horizontalLayout_19.addWidget(self.bnDeleteAd)
        self.line_5 = QtGui.QFrame(self.tabAdmin)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_19.addWidget(self.line_5)
        self.bnSaveAd = QtGui.QPushButton(self.tabAdmin)
        self.bnSaveAd.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                              "background-color: rgb(155, 162, 255);\n"
                                              "background-color: rgb(85, 170, 255);"))
        self.bnSaveAd.setObjectName(_fromUtf8("bnSaveAd"))
        self.horizontalLayout_19.addWidget(self.bnSaveAd)
        self.line_18 = QtGui.QFrame(self.tabAdmin)
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.horizontalLayout_19.addWidget(self.line_18)
        self.bnCancelAd = QtGui.QPushButton(self.tabAdmin)
        self.bnCancelAd.setStyleSheet(_fromUtf8("background-color: rgb(192, 196, 255);\n"
                                                "background-color: rgb(155, 162, 255);\n"
                                                "background-color: rgb(85, 170, 255);"))
        self.bnCancelAd.setObjectName(_fromUtf8("bnCancelAd"))
        self.horizontalLayout_19.addWidget(self.bnCancelAd)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.line_13 = QtGui.QFrame(self.tabAdmin)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout_6.addWidget(self.line_13)
        self.labelDesignedAd = QtGui.QLabel(self.tabAdmin)
        self.labelDesignedAd.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 127);\n"
                                                     "color: rgb(255, 0, 0);\n"
                                                     "font: 8pt \"Lucida Handwriting\";"))
        self.labelDesignedAd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDesignedAd.setObjectName(_fromUtf8("labelDesignedAd"))
        self.verticalLayout_6.addWidget(self.labelDesignedAd)
        self.tabWidget.addTab(self.tabAdmin, _fromUtf8(""))
        self.tabHelp = QtGui.QWidget()
        self.tabHelp.setObjectName(_fromUtf8("tabHelp"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabHelp)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.toolBox = QtGui.QToolBox(self.tabHelp)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 705, 276))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.calendarWidget = QtGui.QCalendarWidget(self.page_3)
        self.calendarWidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.verticalLayout_9.addWidget(self.calendarWidget)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.textBrowserAbout = QtGui.QTextBrowser(self.page_5)
        self.textBrowserAbout.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowserAbout.setObjectName(_fromUtf8("textBrowserAbout"))
        self.verticalLayout_13.addWidget(self.textBrowserAbout)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 705, 276))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.textBrowserWhatsNew = QtGui.QTextBrowser(self.page_4)
        self.textBrowserWhatsNew.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowserWhatsNew.setObjectName(_fromUtf8("textBrowserWhatsNew"))
        self.verticalLayout_11.addWidget(self.textBrowserWhatsNew)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.textBrowserContacts = QtGui.QTextBrowser(self.page_6)
        self.textBrowserContacts.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowserContacts.setObjectName(_fromUtf8("textBrowserContacts"))
        self.verticalLayout_15.addWidget(self.textBrowserContacts)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.page_7)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.page_7)
        self.textBrowser_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.verticalLayout_17.addWidget(self.textBrowser_4)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.toolBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.labelDesigned = QtGui.QLabel(self.tabHelp)
        self.labelDesigned.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 127);\n"
                                                   "color: rgb(255, 0, 0);\n"
                                                   "font: 8pt \"Lucida Handwriting\";"))
        self.labelDesigned.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDesigned.setObjectName(_fromUtf8("labelDesigned"))
        self.verticalLayout_8.addWidget(self.labelDesigned)
        self.tabWidget.addTab(self.tabHelp, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.toolBox.setCurrentIndex(4)
        QtCore.QObject.connect(self.bnRefreshAd, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableViewAdmin.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GREEN_TECH", None))
        self.labelGreenTechCl.setText(_translate("MainWindow",
                                                 "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">GREEN-TECH</span></p></body></html>",
                                                 None))
        self.labelGreenGroceryCl.setText(_translate("MainWindow",
                                                    "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">GREEN GROCERY POINT OF SALE SYSTEM</span></p></body></html>",
                                                    None))
        self.labelCashier.setText(_translate("MainWindow", "CASHIER", None))
        self.comboBoxCashier.setItemText(0, _translate("MainWindow", "Cashier_1", None))
        self.comboBoxCashier.setItemText(1, _translate("MainWindow", "Cashier_2", None))
        self.comboBoxCashier.setItemText(2, _translate("MainWindow", "Cashier_3", None))
        self.labelAcct.setText(_translate("MainWindow", "ACCT", None))
        self.comboBoxAcct.setItemText(0, _translate("MainWindow", "Cash", None))
        self.comboBoxAcct.setItemText(1, _translate("MainWindow", "Credit Card", None))
        self.labelDateCl.setText(_translate("MainWindow", "DATE", None))
        self.dateEditCl.setDisplayFormat(_translate("MainWindow", "d/M/yyyy", None))
        self.labelTimeCl.setText(_translate("MainWindow", "TIME", None))
        self.labelSubTotalCl.setText(_translate("MainWindow", "Sub-Total", None))
        self.labelTaxCl.setText(_translate("MainWindow", "Tax", None))
        self.labelDiscountCl.setText(_translate("MainWindow", "Discount", None))
        self.labelTotalCl.setText(_translate("MainWindow", "Total", None))
        self.labelReceivedCl.setText(_translate("MainWindow", "Received", None))
        self.labelBalanceCl.setText(_translate("MainWindow", "Balance", None))
        self.bnNextCustomerCl.setText(_translate("MainWindow", "NEXT CUSTOMER", None))
        self.bnCalculateCl.setText(_translate("MainWindow", "CALCULATE", None))
        self.labelSearchCl.setText(_translate("MainWindow", "Enter the Product to Search:-", None))
        self.bnSearchCl.setText(_translate("MainWindow", "SEARCH", None))
        self.bnAddCl.setText(_translate("MainWindow", "ADD", None))
        self.bnPrintCl.setText(_translate("MainWindow", "PRINT", None))
        self.bnSaveCl.setText(_translate("MainWindow", "SAVE", None))
        self.bnCancelCl.setText(_translate("MainWindow", "CANCEL", None))
        self.bnRefreshCl.setText(_translate("MainWindow", "REFRESH", None))
        self.bnDeleteCl.setText(_translate("MainWindow", "DELETE", None))
        self.labelDesignedCl.setText(_translate("MainWindow", "Designed By: K. A. Muriungi & P.K. Ndung\'u", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClient), _translate("MainWindow", "CLIENT", None))
        self.labelGreenTechAd.setText(_translate("MainWindow",
                                                 "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">GREEN-TECH</span></p></body></html>",
                                                 None))
        self.labelGreenGroceryAd.setText(_translate("MainWindow",
                                                    "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">GREEN GROCERY POINT OF SALE SYSTEM</span></p></body></html>",
                                                    None))
        self.labelAdmin.setText(_translate("MainWindow", "ADMIN", None))
        self.comboBoxAdmin.setItemText(0, _translate("MainWindow", "Admin_1", None))
        self.comboBoxAdmin.setItemText(1, _translate("MainWindow", "Admin_2", None))
        self.labelDateAd.setText(_translate("MainWindow", "DATE", None))
        self.dateEditAd.setDisplayFormat(_translate("MainWindow", "d/M/yyyy", None))
        self.labelTimeAd.setText(_translate("MainWindow", "TIME", None))
        self.labelTotalUnitsAd.setText(_translate("MainWindow", "Total Units", None))
        self.labelTotalAmount.setText(_translate("MainWindow", "Total Amount", None))
        self.bnNewEntryAd.setText(_translate("MainWindow", "NEW ENTRY", None))
        self.bnCalculateAd.setText(_translate("MainWindow", "CALCULATE", None))
        self.bnRefreshAd.setText(_translate("MainWindow", "REFRESH", None))
        self.labelSearchAd.setText(_translate("MainWindow", "Enter the Product to Search:-", None))
        self.bnSearchAd.setText(_translate("MainWindow", "SEARCH", None))
        self.bnPrintAd.setText(_translate("MainWindow", "PRINT", None))
        self.bnDeleteAd.setText(_translate("MainWindow", "DELETE", None))
        self.bnSaveAd.setText(_translate("MainWindow", "SAVE", None))
        self.bnCancelAd.setText(_translate("MainWindow", "CANCEL", None))
        self.labelDesignedAd.setText(_translate("MainWindow", "Designed By: K. A. Muriungi & P.K. Ndung\'u", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdmin), _translate("MainWindow", "ADMIN", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Calendar", None))
        self.textBrowserAbout.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:11pt; font-style:italic; color:#05060a;\">    The GREEN-TECH system works by identifying the product in test. It uses two different sensors to make it possible for the identity of the products hence being able to differentiate different products. Weight of the product is identified by the use of 50kg SEN-10245 Load sensor. Identification of the physical product is done by color sensing mechanism withTCS3200 Color Sensor.  After the product details have been identified and confirmed, the relevant details are then displayed on the display. Since there are some products which may have close to similar color values, the system has a provision for confirmation with parameters already stored in a database.</span><span style=\" font-size:11pt; font-style:italic; color:#05060a;\"> </span><span style=\" font-family:\'Times New Roman,serif\'; font-size:11pt; font-style:italic; color:#05060a;\">                </span></p>\n"
                                                 "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:11pt; font-style:italic; color:#05060a;\">    Once the weight and the product has been measured, the system automatically calculates the cost of the product by the use of designed algorithm specifically meant for specific products. After a certain quantity of product has been sold, the database of the products is updated automatically and the system admin is then able to monitor the stock inlet and outlet. The system is also expected to be able to print receipts which help in referencing the products sold to the customers. We aim to enable grocery chain stores to be centrally managed economically with ease. </span></p></body></html>",
                                                 None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5),
                                 _translate("MainWindow", "About Green-Tech System", None))
        self.textBrowserWhatsNew.setHtml(_translate("MainWindow",
                                                    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">    </span></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">    The GREEN-TECH System is now able  to differentiate more distinct products compared with the early versions of the system.</span></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">    It has also incorporated multiple users as one is now able to log into the system by using the set password and hence wrong transactions done by one user can\'t affect the other user.</span></p></body></html>",
                                                    None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4),
                                 _translate("MainWindow", "What\'s New in Green-Tech System", None))
        self.textBrowserContacts.setHtml(_translate("MainWindow",
                                                    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-style:italic;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">Contact Green-Tech Systems Thru\'</span></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-style:italic;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">+254-718605065 / +254-</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:10pt; font-style:italic; color:#00000a;\">719476252</span></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman,serif\'; font-size:10pt; font-style:italic; color:#00000a;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:10pt; font-style:italic; color:#00000a;\">you can Call, Text or WhatsApp</span></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman,serif\'; font-size:10pt; font-style:italic; color:#00000a;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:10pt; font-style:italic; color:#00000a;\">Email us :</span></p>\n"
                                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman,serif\'; font-size:10pt; font-style:italic; color:#00000a;\"><br /></p>\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"kamkith@gmail.com\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Email Green-Tech Systems </span></a></p>\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:10pt; font-style:italic; color:#00000a;\"> </span></p></body></html>",
                                                    None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6),
                                 _translate("MainWindow", "Green-Tech System Technical Help Center", None))
        self.textBrowser_4.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
                                              "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">    Kithinji A. Muriungi and Peter K. Ndung\'u  are Engineering Students from Moi University - Kenya. They are Undergraduate students taking Bachelor of Engineering (Electrical and Electronics Engineering). They are very passionate about Embedded Systems Design and Automated Systems. Peter is currently in his final year while Kithinji is in his third year of study.</span></p></body></html>",
                                              None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", "Know Developers", None))
        self.labelDesigned.setText(_translate("MainWindow", "Designed By: K. A. Muriungi & P.K. Ndung\'u", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHelp), _translate("MainWindow", "HELP", None))


# Initializing the Whole Window before anything is done

if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    ex = Ui_MainWindow()
    ex.show()
    sys.exit(app.exec_())
